// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tapToVtoe() {
    driver.get("https://mycutebaby.in/contest/participant/?n=61c48a8d241cd&utm_source=wsapp_share&utm_campaign=December_2021&utm_medium=shared&utm_term=wsapp_shared_61c48a8d241cd&utm_content=participant");
    driver.manage().window().setSize(new Dimension(998, 674));
    js.executeScript("window.scrollTo(0,1550)");
    js.executeScript("window.scrollTo(0,2050)");
    js.executeScript("window.scrollTo(0,2650)");
    {
      WebElement element = driver.findElement(By.cssSelector(".icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".text")).click();
    js.executeScript("window.scrollTo(0,2550)");
    driver.close();
  }
}
